
server:
  port: 8081

spring:
  application:
    name: reservationInventory

  graphql:
    graphiql:
      enabled: true

  profiles:
    active: dev

  threads:
    virtual:
      enabled: true

mq:
  queues:
    reservationInventory: reservationInventory

featuretoggle:
  EnvName: ${FEATURE_TOGGLE_NAME}
  InstanceId: ${INSTANCE_ID}
  Url: ${FEATURE_TOGGLE_URL}