
server:
  port: 8080

spring:
  application:
    name: reservationInventory

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:password}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

  mail:
    host: ${MAIL_HOST:smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  graphql:
    graphiql:
      enabled: true

api:
  viacep:
    url: ${API_VIACEP_URL:https://viacep.com.br/ws}

mq:
  queues:
    reservationInventory: reservationInventory

featuretoggle:
  EnvName: ${FEATURE_TOGGLE_NAME}
  InstanceId: ${INSTANCE_ID}
  Url: ${FEATURE_TOGGLE_URL}
