
# Application configuration for production environment

spring:

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: ${DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    database-platform: ${DATASOURCE_PLATFORM}

api:
  inventory-management:
    url: ${API_INVENTORY_MANAGEMENT_URL}
  email-service:
    url: ${API_EMAIL_SERVICE_URL}
  user-management-service:
    url: ${API_USER_MANAGEMENT_SERVICE_URL}
  viacep:
    url: ${API_VIACEP_URL}