
# Application configuration for development environment

spring:

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

api:
  inventory-management:
    url: ${API_INVENTORY_MANAGEMENT_URL:http://localhost:8080/BIM-WS/InventoryManagementWS}
  email-service:
    url: ${API_EMAIL_SERVICE_URL:http://localhost:8083/api/v1/emails}
  user-management-service:
    url: ${API_USER_MANAGEMENT_SERVICE_URL:http://localhost:8084/api/v1/users}
  viacep:
    url: ${API_VIACEP_URL:https://viacep.com.br/ws}